version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      github_actions:
        patterns:
          - "*"
    commit-message:
      prefix: "ci"
    open-pull-requests-limit: 5

  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      maven:
        patterns:
          - "*"
    commit-message:
      prefix: "chore(java)"
    open-pull-requests-limit: 5
