# ------------------------------------------------------------
# SonarCloud Project Configuration
# ------------------------------------------------------------
# SPDX-License-Identifier: AGPL-3.0-only
# SPDX-FileCopyrightText: 2026 Steve Clarke <stephenlclarke@mac.com> - https://xyzzy.tools

sonar.projectKey=stephenlclarke_fixdecoder_java
sonar.projectName=fixdecoder_java
sonar.projectVersion=0.3.0
sonar.projectDescription=FIX Decoder: a high-performance FIX protocol message decoder written in Java.
sonar.organization=stephenlclarke
sonar.host.url=https://sonarcloud.io
sonar.sourceEncoding=UTF-8

# ------------------------------------------------------------
# Source and Language Configuration
# ------------------------------------------------------------
sonar.sources=src/main/java
sonar.tests=src/test/java
sonar.java.binaries=target/classes
sonar.java.test.binaries=target/test-classes
sonar.exclusions=resources/**,target/**,docs/**

# ------------------------------------------------------------
# Test and Coverage Reports
# ------------------------------------------------------------
sonar.junit.reportPaths=target/surefire-reports
sonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml
